### ISSUE TITLE
`hoodie.global.findAll` doesn't accept a function as an argument

### ISSUE THREAD

**Issue by andreruffert** [hoodiehq-archive/hoodie-plugin-global-share#13]
`hoodie.store.findAll()` also accepts a function as an argument for complex queries e.g.

``` js
hoodie.store.findAll(function(object){
  if(object.type === "task" && object.status === "open"){
    return true;
  }
}).done(function (objects) {});
```

It looks like that `hoodie.global.findAll()` doesn't accept a function as an argument.

**The response:** `{"error":"bad_request","reason":"invalid_json"}`

Maybe the problem is that the startkey and endkey GET parameters values are the function itself.

![bildschirmfoto 2014-07-09 um 18 46 35](https://cloud.githubusercontent.com/assets/464300/3527916/e2057d6a-0789-11e4-91ff-f2c64574346f.png)

**Comment by timblack1** [comment]
Is the plugin attempting to create a temporary view per https://wiki.apache.org/couchdb/HTTP_view_API#Temporary_Views?  If so, it would seem it needs to put the function in the `map` rather than `startkey` and `endkey` JSON keys.  But where does that happen in this plugin's code?  It seems to me it must not be in the plugin itself, but in Hoodie's core, because https://github.com/hoodiehq/hoodie-plugin-global-share/blob/master/hoodie.global-share.js#L7 makes me think `hoodie.global` is just a regular frontend `hoodie.store` object instance hooked up to a remote database.

I wonder if https://github.com/hoodiehq/hoodie-plugin-global-share/issues/23 is related.

**Comment by timblack1** [comment]
It looks to me like this plugin's tests don't test hoodie.global.findAll().  I'd like to write a couple tests, and maybe implement what is necessary to pass.  But could I get approval from a core developer that it's worth spending the time on this - @boennemann, @caolan, or @gr2m ?  Specifically, do you intend to use this plugin in the new PouchDB version of Hoodie?

**Comment by timblack1** [comment]
Hm...having trouble getting the test environment set up.  I'm getting an error which says, `ReferenceError: Can't find variable: Hoodie`.  My branch is at https://github.com/timblack1/hoodie-plugin-global-share/tree/feature/test-findall; I've only updated the versions of hoodie, hoodie-server, and hoodie-plugin-users so far, and added `"phantomjs": "^1.9.18"` as a dev dependency.

**Comment by gr2m** [comment]
Hey I'm afraid I can't look into this right now, and will be mostly traveling until end of October. Sorry I can't help better right now, just wanted to let you know

**Comment by timblack1** [comment]
I guess a simple workaround is to call `.findAll(type)`, then filter for the docs I need locally.
